name = "markdowner"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat"]


# Browser Rendering API binding
browser = { binding = "MYBROWSER" }

[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes

[[kv_namespaces]]
binding= "MD_CACHE"
id = "dd8a3d430a3b42fc899f7b83cdb35688"
preview_id = "b37ef3c41fea428891ab4fbb54a642ab"

# Rate limiter removed - authentication provides security

[ai]
binding = "AI"
